controller_frequency: 10

TrajectoryPlannerROS:

  # Unused for this project: please see "dwa_local_planner_params.yaml" instead

  max_vel_x: 1.0
  min_vel_x: -0.1 # To allow for reverse gear

  max_vel_theta: 1.570796
  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 2.0

  vx_samples: 5.0
  vtheta_samples: 10.0

  path_distance_bias: 0.6
  goal_distance_bias: 0.8
  
  occdist_scale: 0.02

  holonomic_robot: false

  meter_scoring: true # To suppress warning
