# Modified from: https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_navigation/param/costmap_common_params.yaml
# Parameters' list: http://wiki.ros.org/costmap2d?distro=noetic

# Resources:
# [1] Zheng, K.: "ROS Navigation Tuning Guide" (2019)
# [2] https://wiki.ros.org/navfn?distro=noetic

transform_tolerance: 0.2

# Enough to prevent bumping into corners while allowing some degree of movement
robot_radius: 0.3
# footprint: [[x0, y0], [x1, y1], ...]
# footprint_padding: 0.01

obstacle_layer:
  enabled: true
  max_obstacle_height: 0.6

  # Voxel grid -specific parameters
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  unknown_threshold: 15
  mark_threshold: 0
  
  combination_method: 1
  track_unknown_space: true  # To allow for global path planning through unknown space [2]

  obstacle_range: 1.0
  raytrace_range: 2.0
  publish_voxel_map: true

  observation_sources: laser_scan_sensor

  laser_scan_sensor:
    sensor_frame: hokuyo
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    max_obstacle_height: 0.6
    min_obstacle_height: 0.05

inflation_layer:
  enabled: true

  # From [1], with a similar combination the robot tends to move in the middle of obstacles
  cost_scaling_factor: 2.58
  inflation_radius: 1.50  # Suggested by paper: 1.75

static_layer:
  enabled: true
