# Modified from: https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_navigation/param/global_costmap_params.yaml
# Parameters' list: http://wiki.ros.org/costmap2d?distro=noetic

global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 2.0
   publish_frequency: 2.0
   width: 20.0
   height: 20.0
   resolution: 0.05
   rolling_window: false
   plugins:
     - {name: static_layer, type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
