# Modified from: https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_navigation/param/local_costmap_params.yaml
# Parameters' list: http://wiki.ros.org/costmap2d?distro=noetic

local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   rolling_window: true
   
   # Width and height also impact the size of the DWA cost cloud in RViz (/move_base/DWAPlannerROS/cost_cloud)
   # Reducing grid size prevents robot's indecisiveness when goal is at the same x-coordinate but in a different room
   width: 6.0
   height: 6.0
   resolution: 0.05
   transform_tolerance: 0.5
   plugins:
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
