# Modified from: https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_navigation/param/move_base_params.yaml
# Parameters' list: http://wiki.ros.org/move_base?distro=noetic

shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_global_planner: "navfn/NavfnROS"

