NavfnROS:

  # Modified from: https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_navigation/param/navfn_global_planner_params.yaml
  # Parameters' list: http://wiki.ros.org/navfn?distro=noetic

  # Resources:
  # [1] Zheng, K.: "ROS Navigation Tuning Guide" (2019)
  # [2] https://wiki.ros.org/navfn?distro=noetic 

  allow_unknown: false  # Disallow plans that traverse unknown space [1] [2]
  planner_window_x: 0.0
  planner_window_y: 0.0
  default_tolerance: 0.0
  visualize_potential: false
